"""associations_cascade_delete

Revision ID: 0f419fe441d2
Revises: 8853dd66c1dd
Create Date: 2025-04-19 23:57:20.093705

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0f419fe441d2"
down_revision: Union[str, None] = "8853dd66c1dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "articles_likes_association_user_id_fkey",
        "articles_likes_association",
        type_="foreignkey",
    )
    op.drop_constraint(
        "articles_likes_association_article_id_fkey",
        "articles_likes_association",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "articles_likes_association",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "articles_likes_association",
        "articles",
        ["article_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "tour_dates_association_date_id_fkey",
        "tour_dates_association",
        type_="foreignkey",
    )
    op.drop_constraint(
        "tour_dates_association_tour_id_fkey",
        "tour_dates_association",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "tour_dates_association",
        "tour_dates",
        ["date_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "tour_dates_association",
        "tours",
        ["tour_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tour_dates_association", type_="foreignkey")
    op.drop_constraint(None, "tour_dates_association", type_="foreignkey")
    op.create_foreign_key(
        "tour_dates_association_tour_id_fkey",
        "tour_dates_association",
        "tours",
        ["tour_id"],
        ["id"],
    )
    op.create_foreign_key(
        "tour_dates_association_date_id_fkey",
        "tour_dates_association",
        "tour_dates",
        ["date_id"],
        ["id"],
    )
    op.drop_constraint(None, "articles_likes_association", type_="foreignkey")
    op.drop_constraint(None, "articles_likes_association", type_="foreignkey")
    op.create_foreign_key(
        "articles_likes_association_article_id_fkey",
        "articles_likes_association",
        "articles",
        ["article_id"],
        ["id"],
    )
    op.create_foreign_key(
        "articles_likes_association_user_id_fkey",
        "articles_likes_association",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
