"""tour_requests_contact

Revision ID: 4f13a7b447ef
Revises: c8df3360988c
Create Date: 2025-04-16 03:17:34.445816

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f13a7b447ef"
down_revision: Union[str, None] = "c8df3360988c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tour_requests", sa.Column("contact", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tour_requests", "contact")
    # ### end Alembic commands ###
