"""tour_active

Revision ID: 8853dd66c1dd
Revises: c6f81ad03976
Create Date: 2025-04-19 23:04:21.500694

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8853dd66c1dd"
down_revision: Union[str, None] = "c6f81ad03976"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tours", sa.Column("active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tours", "active")
    # ### end Alembic commands ###
