"""article_approved

Revision ID: c6f81ad03976
Revises: 4f13a7b447ef
Create Date: 2025-04-16 22:49:59.924265

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6f81ad03976"
down_revision: Union[str, None] = "4f13a7b447ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles", sa.Column("approved", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "tour_requests", sa.Column("approved", sa.Boolean(), nullable=False)
    )
    op.drop_column("tour_requests", "approve")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tour_requests",
        sa.Column(
            "approve", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("tour_requests", "approved")
    op.drop_column("articles", "approved")
    # ### end Alembic commands ###
