"""tour_requests

Revision ID: c8df3360988c
Revises: 2a77495b70be
Create Date: 2025-04-16 03:14:51.822524

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c8df3360988c"
down_revision: Union[str, None] = "2a77495b70be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tour_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("approve", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("tour_id", sa.Integer(), nullable=False),
        sa.Column("date_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["date_id"], ["tour_dates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tour_id"], ["tours.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tour_requests")
    # ### end Alembic commands ###
